version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  service.api:
    image: ${DOCKER_REGISTRY-}serviceapi
    build:
      context: .
      dockerfile: Service.Api/Dockerfile
    depends_on:
      - sqldata

  mvc.client.webapp:
    image: ${DOCKER_REGISTRY-}mvcclientwebapp
    build:
      context: .
      dockerfile: Mvc.Client.WebApp/Dockerfile


  aspnetidentity.sts:
    image: ${DOCKER_REGISTRY-}aspnetidentitysts
    build:
      context: .
      dockerfile: AspNetIdentity.Sts/Dockerfile
    depends_on:
      - sqldata
