version: '3.4'

services:

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - identity-sqldata:/var/opt/mssql

  service.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=PersonDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5037:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identityserver4.sts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=PersonDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  identity-sqldata:
    external: false
